import sqlite3
import streamlit as st

def Create():
    db = st.query_params['db']
    con = sqlite3.connect(f"Users/{db}")
    cur = con.cursor()
    #Create Tables
    cur.execute("Create Table Items(Name varchar(80) primary key, Type varchar(80))")
    cur.execute("Create Table Enhancement(Name varchar(80) references Items(name), xp Integer, type varchar(5))")
    cur.execute("create Table Equipment(Name varchar(80) references Items(name), LevelReq Integer, Type varchar(6))")
    cur.execute("Create Table Armor(Name varchar(80) references Equipment(name), minDef Integer, maxDef Integer)")
    cur.execute("Create Table Weapon(Name varchar(80) references Equipment(name), minAtk Integer, maxAtk Integer)")
    cur.execute("Create Table Enemy(Name varchar(80) Primary key, minLevel Integer, maxLevel Integer, minHp Integer, maxHp Integer, minDef Integer, maxDef Integer)")
    cur.execute("Create Table Area(Name varchar(80) Primary key, FloorNum integer)")
    cur.execute("Create Table Spawns(Enemy varchar(80) references Enemy(Name) not null, AName varchar(80) references Area(Name) not null)")
    cur.execute("Create Table Drops(Item varchar(80) references Items(Name), Enemy varchar(80) references Enemy(Name))")
    cur.execute("Create Table Consumables(Name varchar(80) references Items(Name), Type varchar(20))")
    cur.execute("Create Table AntiAilment(Name varchar(80) references Items(Name))")
    cur.execute("Create Table Cures(Name varchar(80) references AntiAilment(Name), Ailment varchar(30))")
    cur.execute("Create Table Healing(Name varchar(80) references Consumables(Name), Amt integer)")
    cur.execute("Create Table Recipe(Name varchar(80) references items(name) Unique, numItems Integer)")
    cur.execute("Create Table Materials(Name varchar(80) References item(name), Qty Integer, itemNum Integer, Rname varchar(80) references Recipe(name), Unique(Name, Rname))")
    cur.execute("Create Table Inventory(Item varchar(80) references Item(name) Unique, Qty Integer)")
    #F1
    #add items
    cur.execute("Insert into Items Values('small sword', 'equipment')")
    cur.execute("Insert into Items Values('Coarse Stone', 'Material')")
    cur.execute("Insert into Items Values('Bronze Sword', 'Equipment')")
    cur.execute("Insert into Items Values('Boar Hide', 'Material')")
    cur.execute("Insert into Items Values('Bronze Dagger', 'Weapon')")
    cur.execute("Insert into Items Values('Bronze Axe', 'Weapon')")
    cur.execute("Insert into Items Values('Bronze Armor', 'Equipment')")
    cur.execute("Insert into Items Values('Pointed Stinger', 'Material')")
    cur.execute("Insert into Items Values('Wolf Claw', 'Material')")
    cur.execute("Insert into Items Values('Anneal Blade', 'Equipment')")
    cur.execute("Insert into Items Values('Anneal Rapier', 'Equipment')")
    cur.execute("Insert into Items Values('Anneal Hammer', 'Equipment')")
    cur.execute("Insert into Items Values('Anneal Dagger', 'Equipment')")
    cur.execute("Insert into Items Values('Anneal Axe', 'Equipment')")
    cur.execute("Insert into Items Values('Anneal Lance', 'Equipment')")
    cur.execute("Insert into Items Values('Bronze Greaves', 'Equipment')")
    cur.execute("Insert into Items Values('Bronze Lance', 'Equipment')")
    cur.execute("Insert into Items Values('Bronze Mace', 'Equipment')")
    cur.execute("Insert into Items Values('Bronze Rapier', 'Equipment')")
    cur.execute("Insert into Items Values('Mixed Clothes', 'Equipment')")
    cur.execute("Insert into Items Values('Mixed Leggings', 'Equipment')")
    cur.execute("Insert into Items Values('Small Metal Piece', 'Material')")
    #add Enhancement
    #add Equipment
    cur.execute("Insert into Equipment Values('small sword', 1, 'sword')")
    cur.execute("Insert into Equipment Values('Bronze Axe', 1, 'Axe')")
    cur.execute("Insert into Equipment Values('Bronze Sword', 1, 'Sword')")
    cur.execute("Insert into Equipment Values('Anneal Rapier', 10, 'Rapier')")
    cur.execute("Insert into Equipment Values('Bronze Dagger', 1, 'Dagger')")
    cur.execute("Insert into Equipment Values('Anneal Dagger', 10, 'Dagger')")
    cur.execute("Insert into Equipment Values('Bronze Armor', 1, 'Chest')")
    cur.execute("Insert into Equipment Values('Anneal Lance', 10, 'Spear')")
    cur.execute("Insert into Equipment Values('Anneal Blade', 10, 'Sword')")
    cur.execute("Insert into Equipment Values('Bronze Lance', 1, 'Spear')")
    cur.execute("Insert into Equipment Values('Anneal Hammer', 10, 'Mace')")
    cur.execute("Insert into Equipment Values('Bronze Rapier', 1, 'Rapier')")
    cur.execute("Insert into Equipment Values('Anneal Axe', 10, 'Axe')")
    cur.execute("Insert into Equipment Values('Mixed Leggings', 1, 'Leggings')")
    cur.execute("Insert into Equipment Values('Bronze Greaves', 1, 'Leggings')")
    cur.execute("Insert into Equipment Values('Bronze Mace', 1, 'Mace')")
    cur.execute("Insert into Equipment Values('Mixed Clothes', 1, 'Chest')")
    #Add Armor
    cur.execute("Insert into Armor Values('Bronze Armor', 27, 40)")
    cur.execute("Insert into Armor Values('Bronze Greaves', 22, 39)")   
    cur.execute("Insert into Armor Values('Mixed Clothes', 35, 59)")
    cur.execute("Insert into Armor Values('Mixed Leggings', 29, 51)")    
    #Add Weapon
    cur.execute("Insert into Weapon Values('small sword', 47, 118)")
    cur.execute("Insert into Weapon Values('Bronze Sword', 65, 139)")
    cur.execute("Insert into Weapon Values('Bronze Dagger', 67, 137)")
    cur.execute("Insert into Weapon Values('Bronze Axe', 67, 146)")
    cur.execute("Insert into Weapon Values('Anneal Blade', 93, 219)")
    cur.execute("Insert into Weapon Values('Anneal Rapier', 95, 215)")
    cur.execute("Insert into Weapon Values('Anneal Hammer', 93, 219)")
    cur.execute("Insert into Weapon Values('Anneal Dagger', 95, 215)")
    cur.execute("Insert into Weapon Values('Anneal Axe', 95, 230)")
    cur.execute("Insert into Weapon Values('Anneal Lance', 99, 226)")
    cur.execute("Insert into Weapon Values('Bronze Greaves', 69, 143)")
    cur.execute("Insert into Weapon Values('Bronze Lance', 69, 143)")
    cur.execute("Insert into Weapon Values('Bronze Mace', 65, 139)")
    cur.execute("Insert into Weapon Values('Bronze Rapier', 67, 137)")    
    #Add Enemy
    cur.execute("Insert into Enemy Values('Frenzy Boar', 1, 8, 363, 554, 9, 9)")
    cur.execute("Insert into Enemy Values('Stabbing Wasp', 2, 8, 388, 582, 4, 4)")
    cur.execute("Insert into Enemy Values('Dire Wolf', 3, 8, 507, 760, 12, 12)")
    cur.execute("Insert into Enemy Values('Kobold Henchman', 3, 8, 507, 760, 22, 22)")
    cur.execute("Insert into Enemy Values('Little Nepenthes', 4, 4, 882, 882, 9, 9)")
    #Add Area
    cur.execute("Insert into Area Values('Origin Planes', 1)")
    cur.execute("Insert into Area Values('Quest Plains', 1)")
    cur.execute("Insert into Area Values('Rivalry Plains', 1)")
    cur.execute("Insert into Area Values('Quest Planes', 1)")
    cur.execute("Insert into Area Values('Rivalry Planes', 1)")    
    #Add Spawns
    cur.execute("Insert into Spawns Values('Frenzy Boar', 'Origin Planes')")
    cur.execute("Insert into Spawns Values('Frenzy Boar', 'Quest Plains')")
    cur.execute("Insert into Spawns Values('Stabbing Wasp', 'Origin Planes')")
    cur.execute("Insert into Spawns Values('Stabbing Wasp', 'Rivalry Plains')")
    cur.execute("Insert into Spawns Values('Dire Wolf', 'Quest Planes')")
    cur.execute("Insert into Spawns Values('Dire Wolf', 'Rivalry Plains')")
    cur.execute("Insert into Spawns Values('Kobold Henchman', 'Quest Planes')")
    cur.execute("Insert into Spawns Values('Little Nepenthes', 'Rivalry Planes')")
    #Add Drops
    cur.execute("Insert into Drops Values('Coarse Stone', 'Frenzy Boar')")
    cur.execute("Insert into Drops Values('Coarse Stone', 'Stabbing Wasp')")
    cur.execute("Insert into Drops Values('Coarse Stone', 'Dire Wolf')")
    cur.execute("Insert into Drops Values('Coarse Stone', 'Kobold Henchman')")
    cur.execute("Insert into Drops Values('Coarse Stone', 'Little Nepenthes')")
    cur.execute("Insert into Drops Values('Boar Hide', 'Frenzy Boar')")
    cur.execute("Insert into Drops Values('Pointed Stinger', 'Stabbing Wasp')")
    cur.execute("Insert into Drops Values('Wolf Claw', 'Dire Wolf')")
    cur.execute("Insert into Drops Values('Small Metal Piece', 'Kobold Henchman')")
    #Add Consumables
    #Add AntiAilment
    #Add Cures
    #Add Healing
    #Add Recipe
    cur.execute("Insert into Recipe Values('Bronze Sword', 2)")
    cur.execute("Insert into Recipe Values('Bronze Dagger', 3)")
    cur.execute("Insert into Recipe Values('Bronze Axe', 3)")
    cur.execute("Insert into Recipe Values('Bronze Armor', 3)")
    cur.execute("Insert into Recipe Values('Anneal Blade', 3)")
    cur.execute("Insert into Recipe Values('Anneal Rapier', 3)")
    cur.execute("Insert into Recipe Values('Anneal Hammer', 3)")
    cur.execute("Insert into Recipe Values('Anneal Dagger', 3)")
    cur.execute("Insert into Recipe Values('Anneal Axe', 3)")
    cur.execute("Insert into Recipe Values('Anneal Lance', 3)")
    cur.execute("Insert into Recipe Values('Bronze Greaves', 3)")
    cur.execute("Insert into Recipe Values('Bronze Lance', 3)")
    cur.execute("Insert into Recipe Values('Bronze Mace', 3)")
    cur.execute("Insert into Recipe Values('Bronze Rapier', 3)")
    cur.execute("Insert into Recipe Values('Mixed Clothes', 3)")
    cur.execute("Insert into Recipe Values('Mixed Leggings', 3)")    
    #Add Materials
    cur.execute("Insert into Materials Values('Coarse Stone', 1, 1, 'Bronze Sword')")
    cur.execute("Insert into Materials Values('Boar Hide', 1, 2, 'Bronze Sword')")
    cur.execute("Insert into Materials Values('Coarse Stone', 7, 1, 'Bronze Dagger')")
    cur.execute("Insert into Materials Values('Boar Hide', 3, 2, 'Bronze Dagger')")
    cur.execute("Insert into Materials Values('Coarse Stone', 7, 1, 'Bronze Axe')")
    cur.execute("Insert into Materials Values('Boar Hide', 3, 2, 'Bronze Axe')")
    cur.execute("Insert into Materials Values('Small Metal Piece', 1, 2, 'Anneal Blade')")
    cur.execute("Insert into Materials Values('Coarse Stone', 13, 1, 'Anneal Lance')")
    cur.execute("Insert into Materials Values('Small Metal Piece', 7, 2, 'Anneal Lance')")
    cur.execute("Insert into Materials Values('Coarse Stone', 13, 1, 'Anneal Axe')")
    cur.execute("Insert into Materials Values('Small Metal Piece', 7, 2, 'Anneal Axe')")
    cur.execute("Insert into Materials Values('Coarse Stone', 2, 1, 'Anneal Blade')")
    cur.execute("Insert into Materials Values('Coarse Stone', 13, 1, 'Anneal Dagger')")
    cur.execute("Insert into Materials Values('Small Metal Piece', 7, 2, 'Anneal Dagger')")
    cur.execute("Insert into Materials Values('Coarse Stone', 13, 1, 'Anneal Hammer')")
    cur.execute("Insert into Materials Values('Boar Hide', 7, 2, 'Anneal Hammer')")
    cur.execute("Insert into Materials Values('Coarse Stone', 2, 1, 'Anneal Rapier')")
    cur.execute("Insert into Materials Values('Small Metal Piece', 1, 2, 'Anneal Rapier')")
    cur.execute("Insert into Materials Values('Coarse Stone', 1, 1, 'Bronze Armor')")
    cur.execute("Insert into Materials Values('Boar Hide', 1, 2, 'Bronze Armor')")
    cur.execute("Insert into Materials Values('Pointed Stinger', 3, 2, 'Bronze Greaves')")
    cur.execute("Insert into Materials Values('Coarse Stone', 1, 1, 'Bronze Greaves')")
    cur.execute("Insert into Materials Values('Boar Hide', 1, 2, 'Bronze Greaves')")
    cur.execute("Insert into Materials Values('Coarse Stone', 7, 1, 'Bronze Lance')")
    cur.execute("Insert into Materials Values('Pointed Stinger', 3, 2, 'Bronze Lance')")
    cur.execute("Insert into Materials Values('Coarse Stone', 7, 1, 'Bronze Mace')")
    cur.execute("Insert into Materials Values('Boar Hide', 3, 2, 'Bronze Mace')")
    cur.execute("Insert into Materials Values('Coarse Stone', 1, 1, 'Bronze Rapier')")
    cur.execute("Insert into Materials Values('Pointed Stinger', 1, 2, 'Bronze Rapier')")
    cur.execute("Insert into Materials Values('Coarse Stone', 2, 1, 'Mixed Clothes')")
    cur.execute("Insert into Materials Values('Wolf Claw', 1, 2, 'Mixed Clothes')")
    cur.execute("Insert into Materials Values('Coarse Stone', 2, 1, 'Mixed Leggings')")
    cur.execute("Insert into Materials Values('Wolf Claw', 1, 2, 'Mixed Leggings')")    
    #Add Inventory

    con.commit()